project:
  type: website
  output-dir: docs

website:
  title: "Valentina J. Alaasam, Ph.D."
  navbar:
    background: "#252727"
    foreground: "#e6e9e9"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - mentorship.qmd
      - publications.qmd
      - press.qmd
      - contact.qmd

format:
  html:
    theme: flatly
    mainfont: "Times New Roman"
    fontsize: 1.25rem
    #fontcolor: "#0013d5"
    linkcolor: "#31baaa"
    #monofont: courier new
    css: styles.css
    toc: true
  

editor: visual

